name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-18.04]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: |
        uname -a
        sudo apt -y update
        sudo apt -y upgrade
        sudo apt dist-upgrade
        sudo apt -y install linux-headers-$(uname -r) dkms git bc
    - name: Compile
      run: |
        uname -a
        echo ${{ github.head_ref || github.ref_name }}
        make
