name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          ref: v5.8.7

    - name: Configure
      run: |
        echo ${{ github.ref }}
